COCO_WHOLEBODY_TO_OP = {
    "nose":"nose",
    "left_eye":"LEye",
    "right_eye":"REye",
    "left_ear":"LEar",
    "right_ear":"REar",
    "left_shoulder":"LShoulder",
    "right_shoulder":"RShoulder",
    "left_elbow":"LElbow",
    "right_elbow":"RElbow",
    "left_wrist":"LWrist",
    "right_wrist":"RWrist",
    "left_hip":"LHip",
    "right_hip":"RHip",
    "left_knee":"LKnee",
    "right_knee":"RKnee",
    "left_ankle":"Lankle",
    "right_ankle":"RAnkle",
    "left_big_toe":"LBigToe",
    "left_small_toe":"LSmallToe",
    "left_heel":"LHeel",
    "right_big_toe":"RBigToe",
    "right_small_toe":"RSmallToe",
    "right_heel":"RHeel",
}

OP_TO_COCO_WHOLEBODY = {
    "nose":"nose",
    "LEye":"left_eye",
    "REye":"right_eye",
    "LEar":"left_ear",
    "REar":"right_ear",
    "LShoulder":"left_shoulder",
    "RShoulder":"right_shoulder",
    "LElbow":"left_elbow",
    "RElbow":"right_elbow",
    "LWrist":"left_wrist",
    "RWrist":"right_wrist",
    "LHip":"left_hip",
    "RHip":"right_hip",
    "LKnee":"left_knee",
    "RKnee":"right_knee",
    "Lankle":"left_ankle",
    "RAnkle":"right_ankle",
    "LBigToe":"left_big_toe",
    "LSmallToe":"left_small_toe",
    "LHeel":"left_heel",
    "RBigToe":"right_big_toe",
    "RSmallToe":"right_small_toe",
    "RHeel":"right_heel",
    "neck": None,
    "MidHip": None
}
